version: '3'
services:
    mongo:
        image: mongo:5.0 # 5.0及以上均可
        ports:
            - "27017:27017"
        expose:
            - "27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root" # 初始化数据库的用户名
            MONGO_INITDB_ROOT_PASSWORD: "123456" # 初始化数据库的密码
            TZ: "Asia/Shanghai"
        volumes:
            - "./mongo:/data/db" # 数据库数据存储位置
            - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js" # 初始化数据库脚本
            - "./mongo-keyfile:/etc/mongo-keyfile:ro" # 集群通信密钥
        command: [ "mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile" ] # 集群配置
